### PR TITLE
fix: fix some issues with the initial transport system

### PR DESCRIPTION
**Pull request by UndiedGamer**
TODO: Find a way to disable colors without bloating the `Logger` class with 2 private methods

### CODE REVIEW

**Comment by Swiizyy** [comment]
```typescript
import { appendFile } from 'node:fs/promises';
import { container } from '@sapphire/pieces';
import { LogLevel } from '@sapphire/framework';

export class LoggerTransport {
	public fileName: string;
	public loglevel: LogLevel;
	public constructor(options: TransporterOption) {
		this.fileName = options.file;
		this.loglevel = options.loglevel;
		container.transporters.set(this.loglevel, this);
	}

	public async transport(message: string) {
		await appendFile(this.fileName, `${message}\n`);
	}
}

export interface TransporterOption {
	file: string;
	loglevel: LogLevel;
}
```

👇

```typescript
import { appendFile } from 'node:fs/promises';
import { container } from '@sapphire/pieces';
import { LogLevel } from '@sapphire/framework';

export class LoggerTransport {
	public fileName: string;
	public loglevel: LogLevel;
	public constructor(options: TransporterOption) {
		this.fileName = options.file;
		this.loglevel = options.loglevel;
	}

	public async transport(message: string) {
		await appendFile(this.fileName, `${message}\n`);
	}
}

export interface TransporterOption {
	file: string;
	loglevel: LogLevel;
}
```

**Review by Swiizyy — CHANGES_REQUESTED** [review]
- Remove this `container.transporters.set(this.loglevel, this)` in `LoggerTransport.ts`
- Add this  `container.transporters = new Collection` in `Logger.ts`
-  ```typescript
		if (options.transports) {
			container.transporters = new Collection();
			for (const transport of options.transports) {
				container.transporters.set(
					transport.loglevel,
					new LoggerTransport({
						file: transport.file,
						loglevel: transport.loglevel
					})
				);
			}
		}

**Comment by UndiedGamer** [comment]
@Swiizyy none of that causes an issue, now the actual issue is with colorette appending those color unicodes

**Comment by favna** [comment]
Converted to draft because of the todo

**Comment by favna** [comment]
As discussed in DMs, we are closing this PR.

**Pull request closed without merging**
