### PR TITLE
fix(i18next): Fix augments

### PR DESCRIPTION
**Pull request by Swiizyy**
Repair of module de Declarations that do not work after the last update.

### CODE REVIEW

**Review by vladfrangu — APPROVED** [review]

**Comment by favna** [comment]
It should still work with the latest update, unless you're not calling the `/register` import...

**Comment by favna** [comment]
https://github.com/sapphiredev/plugins/assets/4019718/5c1212e3-a1d5-483a-b071-3db535c6dbac

It works just fine for me

```json
{
  "name": "with-typescript-recommended",
  "version": "1.0.0",
  "main": "dist/index.js",
  "author": "@sapphire",
  "license": "UNLICENSE",
  "type": "module",
  "dependencies": {
    "@sapphire/decorators": "^6.0.2",
    "@sapphire/discord-utilities": "^3.1.0",
    "@sapphire/discord.js-utilities": "7.0.1",
    "@sapphire/fetch": "^2.4.1",
    "@sapphire/framework": "^4.5.3",
    "@sapphire/plugin-api": "^5.1.1",
    "@sapphire/plugin-editable-commands": "^3.0.3",
    "@sapphire/plugin-logger": "^3.0.6",
    "@sapphire/plugin-subcommands": "^4.2.0",
    "@sapphire/time-utilities": "^1.7.10",
    "@sapphire/type": "^2.4.0",
    "@sapphire/utilities": "^3.13.0",
    "@skyra/env-utilities": "^1.2.1",
    "colorette": "^2.0.20",
    "discord-api-types": "^0.37.54",
    "discord.js": "^14.13.0"
  },
  "devDependencies": {
    "@sapphire/plugin-i18next": "^5.0.5",
    "@sapphire/prettier-config": "^2.0.0",
    "@sapphire/ts-config": "^4.0.1",
    "@types/node": "^20.5.4",
    "@types/ws": "^8.5.5",
    "prettier": "^3.0.2",
    "tsc-watch": "^6.0.4",
    "typescript": "^5.1.6"
  },
  "scripts": {
    "build": "tsc",
    "watch": "tsc -w",
    "start": "node --preserve-symlinks dist/index.js",
    "dev": "yarn build && yarn start",
    "watch:start": "tsc-watch --onSuccess \"yarn start\"",
    "format": "prettier --write ."
  },
  "packageManager": "yarn@3.6.2"
}
```

```json
{
  "extends": "@sapphire/ts-config/extra-strict",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist",
    "moduleResolution": "node16",
    "tsBuildInfoFile": "dist/.tsbuildinfo"
  },
  "include": ["src"]
}

```

**Comment by DemonWayne** [comment]
I think the issue is in tsconfig. In my case, setting `moduleResolution` to `node16` (was`Node`) helped to get rid of registry error.

**Comment by favna** [comment]
> I think the issue is in tsconfig. In my case, setting `moduleResolution` to `node16` (was`Node`) helped to get rid of registry error.

Potentially Swizzy updated to TS 5.2 without accounting for the breaking changes it introduced which would explain it. His issue will then also be resolved by https://github.com/sapphiredev/utilities/pull/637

**Pull request closed without merging**
