### PR TITLE
refactor: node-fetch to undici

### PR DESCRIPTION
**Pull request by KhafraDev**
Follow up to https://github.com/sapphiredev/plugins/pull/143 (and https://github.com/discordjs/discord.js/pull/6586)

### CODE REVIEW

**Comment by Favna** [comment]
It's that easy? wow...

**Comment by Favna** [comment]
@sapphiredev pack

**Comment by KhafraDev** [comment]
> 
> 
> It's that easy? wow...

It should be, hopefully :)

**Comment by Favna** [comment]
I'll do a test using that PR deploy above tomorrow or later this week but whatever the case we'll be sure to land this before the soon scheduled release of Sapphire v-Next

**Comment by KhafraDev** [comment]
Sounds good, although both [Web streams](https://nodejs.org/dist/latest-v16.x/docs/api/webstreams.html#webstreams_web_streams_api) and [Blob](https://nodejs.org/dist/latest-v16.x/docs/api/buffer.html#buffer_class_blob) are both considered experimental currently which is causing the holdup to the discordjs pr.

**Review by vladfrangu — DISMISSED** [review]
Well that's shockingly easy

**Comment by kyranet** [comment]
There are merge conflicts, please rebase.

**Comment by KhafraDev** [comment]
any idea how to fix the merge conflicts? they're not showing on my side, only here

**Comment by UndiedGamer** [comment]
That pr in djs is closed, now what

**Comment by kyranet** [comment]
You wait for the one in /rest

**Comment by Rexogamer** [comment]
(for reference, the relevant pr is discordjs/discord.js#7747)

**Review by kyranet — DISMISSED** [review]

**Comment by kyranet** [comment]
There are merge conflicts that need resolving, but otherwise LGTM.

**Comment by KhafraDev** [comment]
Okay should be relatively good, still not familiar with yarn so I don't really know where the types change occurred (and I'm a little lazy)

Also I committed these changes directly to my fork's main branch, which didn't make anything easier 😐

**Comment by favna** [comment]
FYI @KhafraDev this is scheduled for v4 so it won't be merged until we're closer to bringing that version out which will be a while. It's good to have ready nonetheless.

**Review by favna — APPROVED** [review]

**Pull request merged**
